bbs/urls.py
from django.conf.urls import url
from bbs import views
urlpatterns = [
    url(r'^',views.add_article),
    url(r'^comment_tree/(?P<article_pk>\d+)/',views.comment_tree),
    url(r'^comment/',views.comment),
    url(r'^up_down/',views.up_down),
    url(r'(?P<username>\w+)/article/(?P<pk>\d+)',views.article_Detail),
    # 如果不加?P<username>是位置参数，home（request，args），如果加了是命名参数，home（request,username）
    url(r'(?P<username>\w+)',views.home),
]

blog_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from bbs.views import register,index,login,register_ajax,get_valid_img,login_out,upload
from bbs import urls as  blog_url
from  bbs import  views
# 导入media
from django.views.static import serve
from django.conf import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^reg/',register),
    url(r'^index/',index),
    url(r'^login/',login),
    url(r'^login_out/',login_out),
    url(r'^reg_ajax/',register_ajax),
    url(r'^get_valid_img/',get_valid_img),
    # 二级路由，将所有blog开头的路由，都交给app下面的urls处理
    url(r'^blog/',include( blog_url)),
    # media相关的路由设置
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    url(r'^upload/uplaod/',upload),
]

bbs/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.jpg", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)
    blog = models.OneToOneField(to="Blog", to_field="nid", null=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)  # 个人博客标题
    site = models.CharField(max_length=32, unique=True)  # 个人博客后缀
    theme = models.CharField(max_length=32)  # 博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog", to_field="nid")  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog", to_field="nid")  # 所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题")  # 文章标题
    desc = models.CharField(max_length=255)  # 文章描述
    create_time = models.DateTimeField()  # 创建时间

    # 评论数
    comment_count = models.IntegerField(verbose_name="评论数", default=0)
    # 点赞数
    up_count = models.IntegerField(verbose_name="点赞数", default=0)
    # 踩
    down_count = models.IntegerField(verbose_name="踩数", default=0)
    category = models.ForeignKey(to="Category", to_field="nid", null=True)
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    tags = models.ManyToManyField(  # 中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),  # 注意顺序！！！
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid")

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    tag = models.ForeignKey(to="Tag", to_field="nid")

    def __str__(self):
        return "{}-{}".format(self.article.title, self.tag.title)

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True)
    article = models.ForeignKey(to="Article", null=True)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True)  # blank=True 在django admin里面可以不填

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

templates/add_article.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/jquery-3.3.1.js"></script>
</head>

<div>
    <form action="/blog/backend/add_article/" method="post">
        <div>
            <label for="">文章标题
                <input type="text">
            </label>
        </div>
        <div>
            <label for="">文章内容</label>
        </div>
          <textarea name="" id="article_content" cols="30" rows="10"></textarea>
         <input type="submit" value="提交">
    </form>
</div>

<body>
<script src="/static/kindeditor/kindeditor-all.js"></script>
<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script charset="utf-8" src="/editor/kindeditor.js"></script>
<script>
        KindEditor.ready(function(K) {
                window.editor = K.create('#article_content',{
                    uploadJson:'upload/',
                    extraFileUploadParams : {
                         csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    }
                });

        });
</script>

</body>
</html>

templates/article_detail.html
{% extends 'base.html' %}
{% block page-main %}
    <h2>{{ article.title }}</h2>
    <p>{{ article.articledetail.content }}</p>
    {#    点赞/踩#}
    <div id="div_digg" class="info" username="{{ request.user.username }}">
        <div class="diggit action">
            <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
        </div>
        <div class="buryit action">
            <span class="burynum" id="bury_count">{{ article.down_count }}</span>
        </div>
        <div class="clear"></div>
        <div class="diggword" id="digg_tips" style="color: red;"></div>

    </div>
{#    评论树#}
    <div class="comment_tree clear">
        评论树：
        <hr>
    </div>
{#    评论楼#}
    <div  class="comment_floor clear" >
        <p>评论列表:</p>
        <hr>
        <ul class="list-group">
            {% for comment in comment_list %}
                <li class="list-group-item">
                    <div>
                         <a href="">#{{ forloop.counter }}楼</a>&nbsp;&nbsp;
                         <span>{{ comment.create_time|date:'Y-m-d H:i' }}</span>&nbsp;&nbsp;
                         <a href="">{{ comment.user.username }}</a>&nbsp;&nbsp;
                         <span  class="pull-right child_comment " comment_pk="{{ comment.pk }}"comment_user="{{ comment.user.username }}">回复</span>
                    </div>
                        {% if comment.parent_comment_id %}
                            <div class="parent_comment well">
                            <p>{{ comment.parent_comment.user.username }}:{{ comment.parent_comment.content }}</p>
                         </div>
                        {% endif %}

                <div>
                    {{ comment.content }}
                </div>
                </li>
            {% endfor %}
        </ul>

    </div>
    {#    发表评论#}
    {% if request.user.username %}
        <div class="comment_submit">
            <div class="clear">发表评论</div>
            <p>昵称：<input type="text" disabled="disabled" size="50" value="{{ request.user.username }}"></p>
            <div>评论内容:</div>
            <div>
                <textarea class="comment_info" name="" id="" cols="55" rows="10"></textarea>
            </div>
            <button class="reply_comment">回复评论</button>
        </div>
    {% endif %}
    <script>
{#        评论树#}
        $.ajax({
            url:'/blog/comment_tree/{{ article.pk }}/',
            type:'post',
            data:{
                csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
            },
            success:function (data) {
                console.log(data)
               $.each(data,function (index,comment_dict) {
                    var s='<div style="margin-left: 20px;"   class="comment_item" comment_id="'+comment_dict.pk+'"> <span class="content">'+comment_dict.content+'</span></div>';
                   if (comment_dict.parent_comment_id){
                       pid=comment_dict.parent_comment_id;
                        $('[comment_id='+pid+']').append(s)
                   }
                   else{
                       $('.comment_tree').append(s)
                   }
               })
            }
        });
        {#        点赞/踩#}
        $(".action").click(function () {
            if ($('.info').attr("username")) {
                var is_up = $(this).hasClass('diggit');
                var article_pk = '{{ article.pk }}';
                $.ajax(
                    {
                        url: '/blog/up_down/',
                        type: 'post',
                        data: {
                            is_up: is_up,
                            article_pk: article_pk,
                            csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                        },
                        success: function (data) {
                            if (data.state) {
                                if (is_up) {
                                    var val = $('.diggnum').text();
                                    val = parseInt(val) + 1;
                                    $('.diggnum').text(val)
                                }
                                else {
                                    var val = $('.burynum').text();
                                    val = parseInt(val) + 1;
                                    $('.burynum').text(val)
                                }
                            }
                            else {
                                if (data.is_up) {
                                    $('.diggword').html('你已经点赞了')
                                }
                                else {
                                    $('.diggword').html('你已经踩了')
                                }
                                setTimeout(function () {
                                    $('.diggword').html('')
                                }, 1000)
                            }
                        }
                    }
                )
            }
            else {
                location.href = '/login'
            }
        });
{#        评论#}
        var pid="";
        $('.reply_comment').click(function () {
            if (pid){
                var slice_begin=$('.comment_info').val().indexOf('\n')+1;
                var comment_info=$('.comment_info').val().slice(slice_begin)
            }
            else{
                 var comment_info=$('.comment_info').val();
            }
            var article_pk="{{ article.pk }}";
            $.ajax({
                url:'/blog/comment/',
                type:'post',
                data:{
                    article_pk:article_pk,
                    comment_info:comment_info,
                    pid:pid,
                     csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                },
                success:function (data) {
{#                    清空文本内容#}
                   $('.comment_info').val('');
                   pid=""
                }
            })
        });
{#        子评论#}
        $('.child_comment').click(function () {
                $('.comment_info').focus();
                pid=$(this).attr('comment_pk');
                  var comment_user=$(this).attr('comment_user');
                 $('.comment_info').val('@'+comment_user+'\n')
        })
    </script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{{ user_obj.username }}的个人主页</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/setupajax.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/static/mystyle.css">
    <link rel="stylesheet" href="/static/{{ user_obj.blog.theme }}">
</head>
<body>
<div class="home-header">
    <p>{{ user_obj.blog.title }}</p>
</div>
<div class="container">
    <div class="row">
        {#        左侧分类开始#}
        <div class="col-md-2">
          {% load my_tags %}

           {% get_left_menu user_obj.username %}
        </div>
        {#        左侧分类结束#}
        {#        中间文章部分开始#}
        <div class="col-md-8">
            {% block page-main %}
            
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block page-main %}
   {% for article in article_list %}
                <div class="article">
                    <h3><a href="/blog/{{ user_obj.username }}/article/{{ article.pk }}">{{ article.title }}</a></h3>
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object auth_img" src="/media/{{ article.user.avatar }}" alt="...">
                            </a>
                        </div>
                        <div class="media-body">
                            <p>{{ article.desc }}</p>
                        </div>
                        <div class="media-bottom">
                            <span id="s1"><a href="/blog/{{ article.user.username }}">{{ article.user.username }}</a>发布于</span>
                            <span>{{ article.create_time |date:'Y-m-d H:i:s' }}</span>
                            <span class=" glyphicon glyphicon-option-horizontal ">评论({{ article.comment_count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count }})</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>INDEX</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css">
</head>
<body>
{#导航栏开始#}
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {#      左边导航栏开始#}
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            {#        右边导航栏开始#}
            <ul class="nav navbar-nav navbar-right">
                {#            用户已经登录#}
                {% if request.user.username %}
                    <li><a href="#">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                    <li><a href="/login_out/">注销</a></li>
                    {#            用户未登录#}
                {% else %}
                    <li><a href="/login/">登录</a></li>
                    <li><a href="/reg/">注册</a></li>
                {% endif %}
            </ul>
            {#        右边导航栏结束#}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
{#导航栏结束#}

<div class="container">
    <div class="row">
        {#        左侧广告位置#}
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">广告一</div>
                <div class="panel-body">
                    广告一内容
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">广告二</div>
                <div class="panel-body">
                    这是广告二的内容
                </div>
            </div>
        </div>
        {#        中间文章部分#}
        <div class="col-md-8">
            {% for article in all_article %}
                <div class="article">
                    <h3><a href="/blog/{{article.user.username}}/article/{{ article.pk}}">{{ article.title }}</a></h3>
                    <div class="media">
                        <div class="media-left">
                            <a href="#">
                                <img class="media-object auth_img" src="/media/{{ article.user.avatar}}" alt="...">
                            </a>
                        </div>
                        <div class="media-body">
                           <p>{{ article.desc }}</p>
                        </div>
                        <div class="media-bottom">
                            <span id="s1"><a href="/blog/{{article.user.username}}">{{ article.user.username }}</a>发布于</span>
                            <span>{{ article.create_time |date:'Y-m-d H:i:s'}}</span>
                            <span class=" glyphicon glyphicon-option-horizontal ">评论({{ article.comment_count }})</span>
                            <span class="glyphicon glyphicon-thumbs-up">点赞({{ article.up_count}})</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {#        右侧广告部位#}
        <div class="col-md-2">
            <div class="panel panel-primary">
                <div class="panel-heading">广告一</div>
                <div class="panel-body">
                    这是广告一的内容
                </div>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">广告二</div>
                <div class="panel-body">
                    这是广告二的内容
                </div>
            </div>
        </div>
    </div>
</div>
<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/register-ajax.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css/">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="/reg_ajax/" method="post" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group {% if form_obj.username.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.username.id_for_label }}" class="col-sm-2 control-label ">
                        {{ form_obj.username.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors}}</span>
                    </div>
                </div>
                <div class="form-group {% if form_obj.password.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.password.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.password.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors}}</span>
                    </div>
                </div>
                <div class="form-group {% if form_obj.re_pwd.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.re_pwd.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.re_pwd.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.re_pwd }}
                        <span class="help-block">{{ form_obj.re_pwd.errors}}</span>
                    </div>
                </div>
                <div class="form-group {% if form_obj.email.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.email.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.email.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">
                        头像上传
                    </label>
                    <div class="col-sm-10">
                        <label for="id_avatar">
                            <img src="/static/default.jpg" id="avatar_img" >
                        </label>
                        <input type="file" id="id_avatar" name="avatar_file" class="hidden">
                    </div>
                </div>
                <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <input  id="btn_submit" type="button" class="btn btn-primary" value="提交">
                        </div>
                    </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
{#    预览头像#}
{#    头像图片文件发生改变，触发事件#}
    $('#id_avatar').change(function () {
{#        创建一个读取文件的对象#}
        var FileReade=new FileReader();
{#        取到当前选中的文件#}
{#        console.log(this.files[0]);#}
{#        读取选中的文件，#}
        FileReade.readAsDataURL(this.files[0]);//读取文件是需要时间的
{#        等待文件读取完毕#}
        FileReade.onload=function () {
            //读取完毕后，将上传的图片加载到src中
            $('#avatar_img').attr('src',FileReade.result)
        }
    });

{#    鼠标点击输入框是移除所有报错和input框颜色#}
    $('form input').focus(function () {
        $(this).parent().parent().removeClass('has-error');
        $(this).next().text('')
    })
</script>
{#ajax提交#}
<script>
    $('#btn_submit').on('click',function () {
        var formdata=new FormData();
        formdata.append('username',$('#id_username').val());
        formdata.append('password',$('#id_password').val());
        formdata.append('re_pwd',$('#id_re_pwd').val());
        formdata.append('email',$('#id_email').val());
        formdata.append('avatar',$('#id_avatar')[0].files[0]);
        formdata.append('csrfmiddlewaretoken',$("[name='csrfmiddlewaretoken']").val());
        $.ajax({
            url:'/reg_ajax/',
            type:'post',
            processData:false,
            contentType:false,
            data: formdata,
            success:function (data) {
                if(data.status ===0 ){
                    location.href=data.msg
                } else{
                    $.each(data.msg,function (k,v) {
                       $('#id_'+k).next().text(v).parent().parent().addClass('has-error')
                    })
                }
            }
        })
    })
</script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/mystyle.css/">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="/reg/" method="post" novalidate enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group {% if form_obj.username.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.username.id_for_label }}" class="col-sm-2 control-label ">
                        {{ form_obj.username.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.username }}
                        <span class="help-block">{{ form_obj.username.errors}}</span>
                    </div>
                </div>
                <div class="form-group {% if form_obj.password.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.password.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.password.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.password }}
                        <span class="help-block">{{ form_obj.password.errors}}</span>
                    </div>
                </div>
                <div class="form-group {% if form_obj.re_pwd.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.re_pwd.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.re_pwd.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.re_pwd }}
                        <span class="help-block">{{ form_obj.re_pwd.errors}}</span>
                    </div>
                </div>
                <div class="form-group {% if form_obj.email.errors.0 %}has-error{% endif %}">
                    <label for="{{ form_obj.email.id_for_label }}" class="col-sm-2 control-label">
                        {{ form_obj.email.label }}
                    </label>
                    <div class="col-sm-10">
                        {{ form_obj.email }}
                        <span class="help-block">{{ form_obj.email.errors}}</span>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label">
                        头像上传
                    </label>
                    <div class="col-sm-10">
                        <label for="id_avatar">
                            <img src="/static/default.jpg" id="avatar_img" >
                        </label>
                        <input type="file" id="id_avatar" name="avatar_file" class="hidden">
                    </div>
                </div>
                <div class="form-group">
                        <div class="col-sm-10 col-sm-offset-2">
                            <input  type="submit" class="btn btn-primary" value="提交">
                        </div>
                    </div>
            </form>
        </div>
    </div>
</div>
<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script>
{#    预览头像#}
{#    头像图片文件发生改变，触发事件#}
    $('#id_avatar').change(function () {
{#        创建一个读取文件的对象#}
        var FileReade=new FileReader();
{#        取到当前选中的文件#}
        console.log(this.files[0]);
{#        读取选中的文件，#}
        FileReade.readAsDataURL(this.files[0]);//读取文件是需要时间的
{#        等待文件读取完毕#}
        FileReade.onload=function () {
            //读取完毕后，将上传的图片加载到src中
            $('#avatar_img').attr('src',FileReade.result)
        }
    });
{#    鼠标点击输入框是移除所有报错和input框颜色#}
    $('form input').focus(function () {
        $(this).parent().parent().removeClass('has-error');
        $(this).next().text('')
    })
</script>
</body>
</html>